name: Image build and push

on:
  push:
    branches: [ "dev" ]
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKERHUB_URL }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_URL }}:${{ github.sha }}
      -
        name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 테스트
          SLACK_COLOR: '#000000' # 메시지 색상
          SLACK_MESSAGE: ${{ steps.get_commit_message.outputs.message }}
          SLACK_TITLE: 'Commit Message'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup Git
        run: |
          git config --global user.name 'jalju0804'
          git config --global user.email 'dlckswn334@naver.com'

      - name: Clone the private repository
        run: |
          git clone https://x-access-token:${{ secrets.MY_PAT }}@${{ secrets.MANIFEST_REPO }}

      - name: Modify files
        run: |
          cd ${{ secrets.MANIFEST_FLODER_URL }}
          echo "Some changes" >> file.txt # 파일 수정 예시

      - name: Push changes
        run: |
          cd ${{ secrets.MANIFEST_FLODER_URL }}
          git add .
          git commit -m "Automated changes"
          git push https://${{ secrets.MY_PAT }}@github.com/${{ secrets.MANIFEST_REPO }}.git
