name: Jacoco

on:
  push:
    branches-ignore:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and analyze
        env:
          APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
          SQL_DDL: ${{ secrets.SQL_DDL }}
          MYSQL_IP: ${{ secrets.MYSQL_IP }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRE: ${{ secrets.ACCESS_TOKEN_EXPIRE }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          REFRESH_TOKEN_EXPIRE: ${{ secrets.REFRESH_TOKEN_EXPIRE }}
          NAVER_CLOUD_SMS_ACCESS_KEY: ${{ secrets.NAVER_CLOUD_SMS_ACCESS_KEY }}
          NAVER_CLOUD_SMS_SECRET_KEY: ${{ secrets.NAVER_CLOUD_SMS_SECRET_KEY }}
          NAVER_CLOUD_SMS_SERVICE_ID: ${{ secrets.NAVER_CLOUD_SMS_SERVICE_ID }}
          NAVER_CLOUD_SMS_SENDER_PHONE: ${{ secrets.NAVER_CLOUD_SMS_SENDER_PHONE }}
        run: ./gradlew test --info